project_id = "dnsbtexptssimysgncca"

[functions.send-push-notification]
verify_jwt = true

[functions.ai-service]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false
